import type { LanguageVariant } from "./types";

export const TYPE_COLORS: Record<string, string> = {
  "Books": "#1D4ED8",
  "Mangas": "#FE7CEC",
  "Comics": "#F97316",
  "Webtoons": "#06B6D4",
  "Manhwa": "#8B5CF6",
  "Movies": "#DC2626",
  "Series": "#2563EB",
  "Music": "#EAB308",
  "Art": "#10B981",
  "Sculptures": "#78716C",
  "Artwork": "#A855F7",
  "Animals": "#84CC16",
  "Creatures": "#9333EA",
  "Board Games": "#B45309",
  "Video Games": "#0EA5E9",
  "Wiki": "#15803D",
  "Games": "#3B82F6",
  "Documents": "#64748B",
  "Others": "#9CA3AF",
  "Academic Area": "#0D9488",
  "Knowledge Area": "#1E40AF",
  "Professional Area": "#7C3AED",
  "Note": "#92487A",
  "Reflection": "#6B7280",
  "Quote": "#9CA3AF",
  "Scientific Experiment": "#16A34A",
  "Log Date": "#8CE4FF",
  "People": "#15803D",
};

export const TYPE_NORMALIZATION: Record<string, string> = {
  "livro": "Books", "livros": "Books", "book": "Books", "books": "Books",
  "manga": "Mangas", "mangá": "Mangas", "mangas": "Mangas", "mangás": "Mangas",
  "hq": "Comics", "comic": "Comics", "comics": "Comics",
  "webtoon": "Webtoons", "webtoons": "Webtoons",
  "manhwa": "Manhwa",
  "filme": "Movies", "movie": "Movies", "movies": "Movies",
  "série": "Series", "series": "Series",
  "musicrelease": "Music", "música": "Music", "musica": "Music", "music": "Music",
  "arte": "Art", "art": "Art",
  "escultura": "Sculptures", "sculpture": "Sculptures",
  "obra de arte": "Artwork", "artwork": "Artwork",
  "ser": "Animals", "animal": "Animals", "animals": "Animals",
  "criatura": "Creatures", "creature": "Creatures", "creatures": "Creatures", "entity": "Creatures",
  "jogo": "Games", "game": "Games", "games": "Games",
  "jogo de tabuleiro": "Board Games", "board game": "Board Games",
  "videogame": "Video Games", "video game": "Video Games",
  "wiki": "Wiki",
  "documento": "Documents", "document": "Documents",
  "acadêmico": "Academic Area", "area academica": "Academic Area", "academic area": "Academic Area",
  "conhecimento": "Knowledge Area", "knowledge area": "Knowledge Area",
  "profissional": "Professional Area", "professional area": "Professional Area",
  "anotação": "Note", "note": "Note",
  "reflexão": "Reflection", "reflection": "Reflection",
  "citação": "Quote", "quote": "Quote",
  "experimento científico": "Scientific Experiment", "scientific experiment": "Scientific Experiment",
  "person": "People", "people": "People",
  "log date": "Log Date",
};

export const LANGUAGE_VARIANTS: Record<string, LanguageVariant> = {
  "en-US": { flag: "🇺🇸", name: "English (US)", color: "#DC2626", field: "englishUSTitle", baseLang: "en" },
  "en-GB": { flag: "🇬🇧", name: "English (UK)", color: "#1E3A8A", field: "englishGBTitle", baseLang: "en" },
  "en-CA": { flag: "🇨🇦", name: "English (Canada)", color: "#EF4444", field: "englishCATitle", baseLang: "en" },
  "en-AU": { flag: "🇦🇺", name: "English (Australia)", color: "#0EA5E9", field: "englishAUTitle", baseLang: "en" },
  "pt-BR": { flag: "🇧🇷", name: "Português (Brasil)", color: "#16A34A", field: "portugueseBRTitle", baseLang: "pt" },
  "pt-PT": { flag: "🇵🇹", name: "Português (Portugal)", color: "#ffbf00", field: "portuguesePTTitle", baseLang: "pt" },
  "es-ES": { flag: "🇪🇸", name: "Español (España)", color: "#F97316", field: "spanishESTitle", baseLang: "es" },
  "es-MX": { flag: "🇲🇽", name: "Español (México)", color: "#16A34A", field: "spanishMXTitle", baseLang: "es" },
  "es-AR": { flag: "🇦🇷", name: "Español (Argentina)", color: "#2563EB", field: "spanishARTitle", baseLang: "es" },
  "fr-FR": { flag: "🇫🇷", name: "Français (France)", color: "#2563EB", field: "frenchFRTitle", baseLang: "fr" },
  "fr-CA": { flag: "🇨🇦", name: "Français (Canada)", color: "#DC2626", field: "frenchCATitle", baseLang: "fr" },
  "ja-JP": { flag: "🇯🇵", name: "日本語", color: "#EC4899", field: "japaneseTitle", baseLang: "ja" },
  "ko-KR": { flag: "🇰🇷", name: "한국어", color: "#8B5CF6", field: "koreanTitle", baseLang: "ko" },
  "zh-CN": { flag: "🇨🇳", name: "中文 (简体)", color: "#EF4444", field: "chineseCNTitle", baseLang: "zh" },
  "zh-TW": { flag: "🇹🇼", name: "中文 (繁體)", color: "#8B5CF6", field: "chineseTWTitle", baseLang: "zh" },
  "de-DE": { flag: "🇩🇪", name: "Deutsch", color: "#F59E0B", field: "germanDETitle", baseLang: "de" },
  "de-AT": { flag: "🇦🇹", name: "Deutsch (Österreich)", color: "#DC2626", field: "germanATTitle", baseLang: "de" },
  "de-CH": { flag: "🇨🇭", name: "Deutsch (Schweiz)", color: "#EF4444", field: "germanCHTitle", baseLang: "de" },
  "it-IT": { flag: "🇮🇹", name: "Italiano", color: "#10B981", field: "italianTitle", baseLang: "it" },
  "ru-RU": { flag: "🇷🇺", name: "Русский", color: "#3B82F6", field: "russianTitle", baseLang: "ru" },
  "la":    { flag: "🏛️", name: "Latīna", color: "#92400E", field: "latinTitle", baseLang: "la" },
  "grc":   { flag: "🏺", name: "Ancient Greek", color: "#1E40AF", field: "ancientGreekTitle", baseLang: "grc" },
  "egy":   { flag: "🔺", name: "Egyptian", color: "#D97706", field: "egyptianTitle", baseLang: "egy" },
  "akk":   { flag: "📜", name: "Akkadian", color: "#78350F", field: "akkadianTitle", baseLang: "akk" },
  "sux":   { flag: "🏺", name: "Sumerian", color: "#064E3B", field: "sumerianTitle", baseLang: "sux" },
  "non":   { flag: "⚔️", name: "Old Norse", color: "#475569", field: "oldNorseTitle", baseLang: "non" },
  "ang":   { flag: "📖", name: "Old English", color: "#6B7280", field: "oldEnglishTitle", baseLang: "ang" },
  "san":   { flag: "🕉️", name: "Sanskrit", color: "#F59E0B", field: "sanskritTitle", baseLang: "san" },
  "phn":   { flag: "🌊", name: "Phoenician", color: "#7C2D12", field: "phoenicianTitle", baseLang: "phn" },
  "arc":   { flag: "📿", name: "Aramaic", color: "#92400E", field: "aramaicTitle", baseLang: "arc" },
  "hbo":   { flag: "✡️", name: "Biblical Hebrew", color: "#1E40AF", field: "biblicalHebrewTitle", baseLang: "hbo" },
  "cop":   { flag: "☦️", name: "Coptic", color: "#B45309", field: "copticTitle", baseLang: "cop" },
  "qya":   { flag: "🌟", name: "Quenya", color: "#A855F7", field: "quenyaTitle", baseLang: "qya" },
  "sjn":   { flag: "🌙", name: "Sindarin", color: "#7C3AED", field: "sindarinTitle", baseLang: "sjn" },
  "khz":   { flag: "⛏️", name: "Khuzdul", color: "#78716C", field: "khuzdulTitle", baseLang: "khz" },
  "blk":   { flag: "👁️", name: "Black Speech", color: "#DC2626", field: "blackSpeechTitle", baseLang: "blk" },
  "tlh":   { flag: "🖖", name: "Klingon", color: "#DC2626", field: "klingonTitle", baseLang: "tlh" },
  "rom":   { flag: "🛸", name: "Romulan", color: "#16A34A", field: "romulanTitle", baseLang: "rom" },
  "vul":   { flag: "🌋", name: "Vulcan", color: "#F59E0B", field: "vulcanTitle", baseLang: "vul" },
  "hut":   { flag: "🐌", name: "Huttese", color: "#84CC16", field: "hutteseTitle", baseLang: "hut" },
  "mdk":   { flag: "🤖", name: "Mando'a", color: "#6B7280", field: "mandoaTitle", baseLang: "mdk" },
  "dot":   { flag: "🐴", name: "Dothraki", color: "#92400E", field: "dothrakiTitle", baseLang: "dot" },
  "hva":   { flag: "🐉", name: "High Valyrian", color: "#DC2626", field: "valyrianTitle", baseLang: "hva" },
  "prs":   { flag: "🐍", name: "Parseltongue", color: "#16A34A", field: "parseltongueTitle", baseLang: "prs" },
  "nav":   { flag: "💙", name: "Na'vi", color: "#0EA5E9", field: "naviTitle", baseLang: "nav" },
  "min":   { flag: "🍌", name: "Minionese", color: "#EAB308", field: "minioneseTitle", baseLang: "min" },
  "nwv":   { flag: "👽", name: "Newspeak", color: "#DC2626", field: "newspeakTitle", baseLang: "nwv" },
  "lap":   { flag: "🐰", name: "Lapine", color: "#78716C", field: "lapineTitle", baseLang: "lap" },
  "epo":   { flag: "⭐", name: "Esperanto", color: "#16A34A", field: "esperantoTitle", baseLang: "epo" },
  "ido":   { flag: "💠", name: "Ido", color: "#2563EB", field: "idoTitle", baseLang: "ido" },
  "ina":   { flag: "🌐", name: "Interlingua", color: "#0891B2", field: "interlinguaTitle", baseLang: "ina" },
  "vol":   { flag: "🗣️", name: "Volapük", color: "#7C3AED", field: "volapukTitle", baseLang: "vol" },
  "jbo":   { flag: "🔷", name: "Lojban", color: "#DC2626", field: "lojbanTitle", baseLang: "jbo" },
  "tok":   { flag: "☀️", name: "Toki Pona", color: "#EAB308", field: "tokiPonaTitle", baseLang: "tok" },
};

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  "en-US": {
    allTypes: "All Types", allSubtypes: "All Subtypes", allStatuses: "All Statuses",
    allLanguages: "All Languages", all: "All", withImage: "With Image", withoutImage: "Without Image",
    title: "Title", creationDate: "Creation Date", fileName: "File Name",
    ascending: "Ascending ↑", descending: "Descending ↓", reset: "Reset",
    previousPage: "⬅️ Previous", nextPage: "Next ➡️", top: "🔝 Top", page: "Page",
    Books: "Books", Mangas: "Mangas", Comics: "Comics", Webtoons: "Webtoons",
    Manhwa: "Manhwa", Movies: "Movies", Series: "Series", Music: "Music",
    Art: "Art", Sculptures: "Sculptures", Artwork: "Artwork", Animals: "Animals",
    Creatures: "Creatures", "Board Games": "Board Games", "Video Games": "Video Games",
    Wiki: "Wiki", Games: "Games", Documents: "Documents", Others: "Others",
    "Academic Area": "Academic Area", "Knowledge Area": "Knowledge Area",
    "Professional Area": "Professional Area", Note: "Note", Reflection: "Reflection",
    Quote: "Quote", "Scientific Experiment": "Scientific Experiment", "Log Date": "Log Date",
    People: "People", openSettings: "Open Settings", noResults: "No notes found.",
    ofItems: "of", items: "items",
  },
  "en-GB": {
    allTypes: "All Types", allSubtypes: "All Subtypes", allStatuses: "All Statuses",
    allLanguages: "All Languages", all: "All", withImage: "With Image", withoutImage: "Without Image",
    title: "Title", creationDate: "Creation Date", fileName: "File Name",
    ascending: "Ascending ↑", descending: "Descending ↓", reset: "Reset",
    previousPage: "⬅️ Previous", nextPage: "Next ➡️", top: "🔝 Top", page: "Page",
    noResults: "No notes found.", ofItems: "of", items: "items",
  },
  "pt-BR": {
    allTypes: "Todos os Tipos", allSubtypes: "Todos os Subtipos", allStatuses: "Todos os Status",
    allLanguages: "Todos os Idiomas", all: "Todos", withImage: "Com Imagem", withoutImage: "Sem Imagem",
    title: "Título", creationDate: "Data de Criação", fileName: "Nome do Arquivo",
    ascending: "Crescente ↑", descending: "Decrescente ↓", reset: "Limpar",
    previousPage: "⬅️ Anterior", nextPage: "Próxima ➡️", top: "🔝 Topo", page: "Página",
    Books: "Livros", Mangas: "Mangás", Comics: "HQs", Webtoons: "Webtoons",
    Manhwa: "Manhwa", Movies: "Filmes", Series: "Séries", Music: "Música",
    Art: "Arte", Sculptures: "Esculturas", Artwork: "Obra de Arte", Animals: "Animais",
    Creatures: "Criaturas", "Board Games": "Jogos de Tabuleiro", "Video Games": "Videogames",
    Wiki: "Wiki", Games: "Jogos", Documents: "Documentos", Others: "Outros",
    "Academic Area": "Área Acadêmica", "Knowledge Area": "Área de Conhecimento",
    "Professional Area": "Área Profissional", Note: "Anotação", Reflection: "Reflexão",
    Quote: "Citação", "Scientific Experiment": "Experimento Científico", "Log Date": "Diário de Bordo",
    People: "Pessoas", noResults: "Nenhuma nota encontrada.", ofItems: "de", items: "itens",
  },
  "es-ES": {
    allTypes: "Todos los Tipos", allSubtypes: "Todos los Subtipos", allStatuses: "Todos los Estados",
    allLanguages: "Todos los Idiomas", all: "Todos", withImage: "Con Imagen", withoutImage: "Sin Imagen",
    title: "Título", creationDate: "Fecha de Creación", fileName: "Nombre de Archivo",
    ascending: "Ascendente ↑", descending: "Descendente ↓", reset: "Restablecer",
    previousPage: "⬅️ Anterior", nextPage: "Siguiente ➡️", top: "🔝 Arriba", page: "Página",
    noResults: "No se encontraron notas.", ofItems: "de", items: "elementos",
  },
  "fr-FR": {
    allTypes: "Tous les Types", allSubtypes: "Tous les Sous-types", allStatuses: "Tous les Statuts",
    allLanguages: "Toutes les Langues", all: "Tous", withImage: "Avec Image", withoutImage: "Sans Image",
    title: "Titre", creationDate: "Date de Création", fileName: "Nom du Fichier",
    ascending: "Croissant ↑", descending: "Décroissant ↓", reset: "Réinitialiser",
    previousPage: "⬅️ Précédent", nextPage: "Suivant ➡️", top: "🔝 Haut", page: "Page",
    noResults: "Aucune note trouvée.", ofItems: "sur", items: "éléments",
  },
  "ja-JP": {
    allTypes: "すべてのタイプ", allSubtypes: "すべてのサブタイプ", allStatuses: "すべてのステータス",
    allLanguages: "すべての言語", all: "すべて", withImage: "画像あり", withoutImage: "画像なし",
    title: "タイトル", creationDate: "作成日", fileName: "ファイル名",
    ascending: "昇順 ↑", descending: "降順 ↓", reset: "リセット",
    previousPage: "⬅️ 前へ", nextPage: "次へ ➡️", top: "🔝 トップ", page: "ページ",
    noResults: "ノートが見つかりません。", ofItems: "/", items: "件",
  },
  "de-DE": {
    allTypes: "Alle Typen", allSubtypes: "Alle Untertypen", allStatuses: "Alle Status",
    allLanguages: "Alle Sprachen", all: "Alle", withImage: "Mit Bild", withoutImage: "Ohne Bild",
    title: "Titel", creationDate: "Erstellungsdatum", fileName: "Dateiname",
    ascending: "Aufsteigend ↑", descending: "Absteigend ↓", reset: "Zurücksetzen",
    previousPage: "⬅️ Zurück", nextPage: "Weiter ➡️", top: "🔝 Oben", page: "Seite",
    noResults: "Keine Notizen gefunden.", ofItems: "von", items: "Elementen",
  },
  "zh-CN": {
    allTypes: "所有类型", allSubtypes: "所有子类型", allStatuses: "所有状态",
    allLanguages: "所有语言", all: "全部", withImage: "有图片", withoutImage: "无图片",
    title: "标题", creationDate: "创建日期", fileName: "文件名",
    ascending: "升序 ↑", descending: "降序 ↓", reset: "重置",
    previousPage: "⬅️ 上一页", nextPage: "下一页 ➡️", top: "🔝 顶部", page: "页",
    noResults: "未找到笔记。", ofItems: "/", items: "条",
  },
  "ko-KR": {
    allTypes: "모든 유형", allSubtypes: "모든 하위 유형", allStatuses: "모든 상태",
    allLanguages: "모든 언어", all: "전체", withImage: "이미지 있음", withoutImage: "이미지 없음",
    title: "제목", creationDate: "생성일", fileName: "파일 이름",
    ascending: "오름차순 ↑", descending: "내림차순 ↓", reset: "초기화",
    previousPage: "⬅️ 이전", nextPage: "다음 ➡️", top: "🔝 맨 위", page: "페이지",
    noResults: "노트를 찾을 수 없습니다.", ofItems: "/", items: "개",
  },
  "it-IT": {
    allTypes: "Tutti i Tipi", allSubtypes: "Tutti i Sottotipi", allStatuses: "Tutti gli Stati",
    allLanguages: "Tutte le Lingue", all: "Tutti", withImage: "Con Immagine", withoutImage: "Senza Immagine",
    title: "Titolo", creationDate: "Data di Creazione", fileName: "Nome File",
    ascending: "Crescente ↑", descending: "Decrescente ↓", reset: "Ripristina",
    previousPage: "⬅️ Precedente", nextPage: "Successivo ➡️", top: "🔝 Top", page: "Pagina",
    noResults: "Nessuna nota trovata.", ofItems: "di", items: "elementi",
  },
  "ru-RU": {
    allTypes: "Все типы", allSubtypes: "Все подтипы", allStatuses: "Все статусы",
    allLanguages: "Все языки", all: "Все", withImage: "С изображением", withoutImage: "Без изображения",
    title: "Название", creationDate: "Дата создания", fileName: "Имя файла",
    ascending: "По возрастанию ↑", descending: "По убыванию ↓", reset: "Сброс",
    previousPage: "⬅️ Назад", nextPage: "Вперёд ➡️", top: "🔝 Наверх", page: "Страница",
    noResults: "Заметки не найдены.", ofItems: "из", items: "элементов",
  },
};

export const DEFAULT_SETTINGS = {
  folders: ["1- Trajectory", "2- Mastery", "3- Wellness", "Core/People"],
  pageSize: 50,
  defaultLanguage: "en-GB",
  defaultSortField: "title",
  defaultSortDir: "asc",
};

export const LANG_FILTER_GROUPS = [
  {
    label: "Modern Languages",
    options: [
      { value: "en", label: "🇬🇧 English" },
      { value: "pt", label: "🇧🇷 Português" },
      { value: "es", label: "🇪🇸 Español" },
      { value: "fr", label: "🇫🇷 Français" },
      { value: "ja", label: "🇯🇵 日本語" },
      { value: "de", label: "🇩🇪 Deutsch" },
      { value: "zh", label: "🇨🇳 中文" },
      { value: "ko", label: "🇰🇷 한국어" },
      { value: "it", label: "🇮🇹 Italiano" },
      { value: "ru", label: "🇷🇺 Русский" },
    ],
  },
  {
    label: "Ancient / Dead Languages",
    options: [
      { value: "la", label: "🏛️ Latin" },
      { value: "grc", label: "🏺 Ancient Greek" },
      { value: "egy", label: "🔺 Egyptian" },
      { value: "akk", label: "📜 Akkadian" },
      { value: "sux", label: "🏺 Sumerian" },
      { value: "non", label: "⚔️ Old Norse" },
      { value: "ang", label: "📖 Old English" },
      { value: "san", label: "🕉️ Sanskrit" },
      { value: "phn", label: "🌊 Phoenician" },
      { value: "arc", label: "📿 Aramaic" },
      { value: "hbo", label: "✡️ Biblical Hebrew" },
      { value: "cop", label: "☦️ Coptic" },
    ],
  },
  {
    label: "Tolkien Languages",
    options: [
      { value: "qya", label: "🌟 Quenya" },
      { value: "sjn", label: "🌙 Sindarin" },
      { value: "khz", label: "⛏️ Khuzdul" },
      { value: "blk", label: "👁️ Black Speech" },
    ],
  },
  {
    label: "Sci-Fi Languages",
    options: [
      { value: "tlh", label: "🖖 Klingon" },
      { value: "rom", label: "🛸 Romulan" },
      { value: "vul", label: "🌋 Vulcan" },
      { value: "hut", label: "🐌 Huttese" },
      { value: "mdk", label: "🤖 Mando'a" },
    ],
  },
  {
    label: "Fantasy Languages",
    options: [
      { value: "dot", label: "🐴 Dothraki" },
      { value: "hva", label: "🐉 High Valyrian" },
      { value: "prs", label: "🐍 Parseltongue" },
      { value: "nav", label: "💙 Na'vi" },
      { value: "lap", label: "🐰 Lapine" },
    ],
  },
  {
    label: "Other Fictional",
    options: [
      { value: "min", label: "🍌 Minionese" },
      { value: "nwv", label: "👽 Newspeak" },
    ],
  },
  {
    label: "Constructed Languages",
    options: [
      { value: "epo", label: "⭐ Esperanto" },
      { value: "ido", label: "💠 Ido" },
      { value: "ina", label: "🌐 Interlingua" },
      { value: "vol", label: "🗣️ Volapük" },
      { value: "jbo", label: "🔷 Lojban" },
      { value: "tok", label: "☀️ Toki Pona" },
    ],
  },
];

export const LANG_SELECT_GROUPS = [
  {
    label: "English Variants",
    options: [
      { value: "en-GB", label: "🇬🇧 English (UK)" },
      { value: "en-US", label: "🇺🇸 English (US)" },
      { value: "en-CA", label: "🇨🇦 English (Canada)" },
      { value: "en-AU", label: "🇦🇺 English (Australia)" },
    ],
  },
  {
    label: "Portuguese Variants",
    options: [
      { value: "pt-BR", label: "🇧🇷 Português (Brasil)" },
      { value: "pt-PT", label: "🇵🇹 Português (Portugal)" },
    ],
  },
  {
    label: "Spanish Variants",
    options: [
      { value: "es-ES", label: "🇪🇸 Español (España)" },
      { value: "es-MX", label: "🇲🇽 Español (México)" },
      { value: "es-AR", label: "🇦🇷 Español (Argentina)" },
    ],
  },
  {
    label: "French Variants",
    options: [
      { value: "fr-FR", label: "🇫🇷 Français (France)" },
      { value: "fr-CA", label: "🇨🇦 Français (Canada)" },
    ],
  },
  {
    label: "German Variants",
    options: [
      { value: "de-DE", label: "🇩🇪 Deutsch (Deutschland)" },
      { value: "de-AT", label: "🇦🇹 Deutsch (Österreich)" },
      { value: "de-CH", label: "🇨🇭 Deutsch (Schweiz)" },
    ],
  },
  {
    label: "Chinese Variants",
    options: [
      { value: "zh-CN", label: "🇨🇳 中文 (简体)" },
      { value: "zh-TW", label: "🇹🇼 中文 (繁體)" },
    ],
  },
  {
    label: "Other Modern Languages",
    options: [
      { value: "ja-JP", label: "🇯🇵 日本語" },
      { value: "ko-KR", label: "🇰🇷 한국어" },
      { value: "it-IT", label: "🇮🇹 Italiano" },
      { value: "ru-RU", label: "🇷🇺 Русский" },
    ],
  },
  {
    label: "Ancient / Dead Languages",
    options: [
      { value: "la", label: "🏛️ Latin" },
      { value: "grc", label: "🏺 Ancient Greek" },
      { value: "egy", label: "🔺 Egyptian" },
      { value: "akk", label: "📜 Akkadian" },
      { value: "sux", label: "🏺 Sumerian" },
      { value: "non", label: "⚔️ Old Norse" },
      { value: "ang", label: "📖 Old English" },
      { value: "san", label: "🕉️ Sanskrit" },
      { value: "phn", label: "🌊 Phoenician" },
      { value: "arc", label: "📿 Aramaic" },
      { value: "hbo", label: "✡️ Biblical Hebrew" },
      { value: "cop", label: "☦️ Coptic" },
    ],
  },
  {
    label: "Tolkien Languages",
    options: [
      { value: "qya", label: "🌟 Quenya" },
      { value: "sjn", label: "🌙 Sindarin" },
      { value: "khz", label: "⛏️ Khuzdul" },
      { value: "blk", label: "👁️ Black Speech" },
    ],
  },
  {
    label: "Sci-Fi Languages",
    options: [
      { value: "tlh", label: "🖖 Klingon" },
      { value: "rom", label: "🛸 Romulan" },
      { value: "vul", label: "🌋 Vulcan" },
      { value: "hut", label: "🐌 Huttese" },
      { value: "mdk", label: "🤖 Mando'a" },
    ],
  },
  {
    label: "Fantasy Languages",
    options: [
      { value: "dot", label: "🐴 Dothraki" },
      { value: "hva", label: "🐉 High Valyrian" },
      { value: "prs", label: "🐍 Parseltongue" },
      { value: "nav", label: "💙 Na'vi" },
      { value: "lap", label: "🐰 Lapine" },
    ],
  },
  {
    label: "Other Fictional",
    options: [
      { value: "min", label: "🍌 Minionese" },
      { value: "nwv", label: "👽 Newspeak" },
    ],
  },
  {
    label: "Constructed Languages",
    options: [
      { value: "epo", label: "⭐ Esperanto" },
      { value: "ido", label: "💠 Ido" },
      { value: "ina", label: "🌐 Interlingua" },
      { value: "vol", label: "🗣️ Volapük" },
      { value: "jbo", label: "🔷 Lojban" },
      { value: "tok", label: "☀️ Toki Pona" },
    ],
  },
];
